apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8sspringboot
  name: k8sspringboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sspringboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8sspringboot
    spec:
      containers:
        - image: k8sspringboot:0.0.1-SNAPSHOT
          name: k8sspringboot
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8sspringboot
  name: k8sspringboot
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8sspringboot
  type: ClusterIP
status:
  loadBalancer: {}
