format_version: 10
pipelines:
  MyFirstPipeline:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-6f6ef59:
        git: https://github.com/gocd-contrib/getting-started-repo.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - defaultStage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          defaultjob:
            timeout: 0
            tabs:
              SomeCustomName: my-artifact.html
            artifacts:
            - build:
                source: my-artifact.html
                destination: ''
            tasks:
            - exec:
                command: ./build
                run_if: passed
